# Generated by Django 6.0.4 on 2026-06-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('insight_type', models.CharField(choices=[('depletion', 'Stock Depletion'), ('dead_stock', 'Dead Stock'), ('pricing', 'Pricing Optimization'), ('anomaly', 'Sales Anomaly')], max_length=20)),
                ('action_text', models.CharField(default='View Details', max_length=50)),
                ('priority', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
