# Generated by Django 5.2.7 on 2026-06-21 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_aiinsight'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='code',
            field=models.CharField(blank=True, max_length=20, verbose_name='branch code'),
        ),
        migrations.AddField(
            model_name='branch',
            name='manager',
            field=models.CharField(blank=True, max_length=100, verbose_name='manager'),
        ),
    ]
