# Generated by Django 5.2.7 on 2026-06-22 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_purchaseorder_purchaseorderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='inventory.branch')),
            ],
            options={
                'verbose_name': 'stock audit',
                'verbose_name_plural': 'stock audits',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAuditItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_quantity', models.IntegerField(verbose_name='physical quantity')),
                ('system_quantity', models.IntegerField(verbose_name='system quantity')),
                ('discrepancy', models.IntegerField(default=0, verbose_name='discrepancy')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockaudit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_items', to='inventory.product')),
            ],
            options={
                'verbose_name': 'stock audit item',
                'verbose_name_plural': 'stock audit items',
            },
        ),
    ]
