# Generated by Django 6.0.5 on 2026-06-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stockaudit_stockaudititem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockaudititem',
            name='audit',
        ),
        migrations.RemoveField(
            model_name='stockaudititem',
            name='product',
        ),
        migrations.DeleteModel(
            name='StockAudit',
        ),
        migrations.DeleteModel(
            name='StockAuditItem',
        ),
    ]
