# Generated by Django 6.0.4 on 2026-06-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='company name')),
                ('contact_person', models.CharField(max_length=100, verbose_name='contact person')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('lifetime_value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='lifetime value')),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='outstanding balance')),
                ('last_order_date', models.DateField(blank=True, null=True, verbose_name='last order date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='company name')),
                ('contact_person', models.CharField(max_length=100, verbose_name='contact person')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('fulfillment_rating', models.IntegerField(default=0, verbose_name='fulfillment rating')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
