# Generated by Django 6.0.5 on 2026-06-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit')], default='cash', max_length=20, verbose_name='payment method'),
        ),
    ]
