# Generated by Django 6.0.5 on 2026-06-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='due date'),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='is paid'),
        ),
        migrations.AddField(
            model_name='sale',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='paid amount'),
        ),
    ]
