# Generated by Django 6.0.5 on 2026-06-24

from django.db import migrations

def populate_existing_sales(apps, schema_editor):
    Sale = apps.get_model('sales', 'Sale')
    # For all existing sales in the system (all were previously cash sales),
    # ensure is_paid is set to True and paid_amount is set to total_amount.
    for sale in Sale.objects.all():
        if sale.payment_method == 'cash' or not sale.payment_method:
            sale.is_paid = True
            sale.paid_amount = sale.total_amount
            sale.save()

class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_due_date_sale_is_paid_sale_paid_amount'),
    ]

    operations = [
        migrations.RunPython(populate_existing_sales, elidable=True),
    ]
